"""Reusable Razorpay REST API client.

Design:

- One ``RazorpayClient`` instance owns one ``httpx.Client`` (connection
  pooling, keep-alive) and is safe to reuse across many requests; it is a
  context manager for explicit lifecycle control.
- Authentication is HTTP Basic, generated by httpx itself — the
  Authorization header is never constructed or logged here.
- All failures surface as typed ``RazorpayError`` subclasses with messages
  built from status codes and Razorpay's structured error fields only.
- Retries are bounded: only transient failures — 429/5xx statuses and
  network errors — on read requests are retried, at most ``max_retries``
  times, honoring ``Retry-After`` when present and capping the delay.
  Permanent failures (authentication, validation, not-found) and writes
  never retry.
- Backoff grows exponentially from a configurable base, is capped at a
  configurable maximum, and is optionally jittered to avoid synchronized
  thundering-herd retries across processes.
- Logging is structured JSON lines carrying endpoint, HTTP method, status,
  request duration, attempt counts, and a per-request correlation id.
  Credentials, Authorization headers, and query strings are never logged.

This layer speaks raw Razorpay payloads; normalization into application
schemas happens in the service layer above it.
"""

import json
import logging
import random
import time
from collections.abc import Callable
from typing import Any
from uuid import uuid4

import httpx

from app.core.config import Settings

from .constants import (
    CONNECT_TIMEOUT_CAP_SECONDS,
    RATE_LIMIT_STATUS,
    RETRY_BACKOFF_MULTIPLIER,
    RETRY_BASE_DELAY_SECONDS,
    RETRY_MAX_DELAY_SECONDS,
    detect_key_mode,
    is_transient_status,
)
from .exceptions import (
    RazorpayAuthenticationError,
    RazorpayConnectionError,
    RazorpayError,
    RazorpayErrorDetail,
    RazorpayInvalidResponseError,
    RazorpayNotFoundError,
    RazorpayRateLimitError,
    RazorpayServerError,
    RazorpayValidationError,
)

logger = logging.getLogger(__name__)

Sleep = Callable[[float], None]
ReadMethodsWithRetries = frozenset({"GET"})
# Full jitter maps a computed backoff into [0, backoff]; the result is
# clamped again by the configured maximum delay.
Jitter = Callable[[float], float]

_AUTHENTICATION_STATUSES = frozenset({401, 403})
_VALIDATION_STATUSES = frozenset({400, 422})
_NOT_FOUND_STATUS = 404


class RazorpayClient:
    """Thin, typed transport to the Razorpay REST API."""

    def __init__(
        self,
        *,
        key_id: str,
        key_secret: str,
        base_url: str,
        timeout_seconds: float,
        max_retries: int = 3,
        retry_base_delay_seconds: float = RETRY_BASE_DELAY_SECONDS,
        retry_max_delay_seconds: float = RETRY_MAX_DELAY_SECONDS,
        jitter: Jitter | None = None,
        transport: httpx.BaseTransport | None = None,
        sleep: Sleep = time.sleep,
    ) -> None:
        if not key_id or not key_secret:
            raise RazorpayError(
                "Razorpay credentials are required to build a client"
            )
        if retry_base_delay_seconds < 0:
            raise ValueError("retry_base_delay_seconds must be non-negative")
        if retry_max_delay_seconds <= 0:
            raise ValueError("retry_max_delay_seconds must be positive")
        if retry_max_delay_seconds < retry_base_delay_seconds:
            raise ValueError(
                "retry_max_delay_seconds must be greater than or equal to "
                "retry_base_delay_seconds"
            )
        self._base_url = base_url.rstrip("/")
        # Only the derived mode is retained — never the raw credentials.
        self._key_mode = detect_key_mode(key_id)
        self._timeout_seconds = timeout_seconds
        self._max_retries = max_retries
        self._retry_base_delay = retry_base_delay_seconds
        self._retry_max_delay = retry_max_delay_seconds
        self._jitter = jitter
        self._sleep = sleep
        self._client = httpx.Client(
            base_url=self._base_url,
            auth=httpx.BasicAuth(username=key_id, password=key_secret),
            timeout=httpx.Timeout(
                timeout_seconds,
                connect=min(timeout_seconds, CONNECT_TIMEOUT_CAP_SECONDS),
            ),
            headers={
                "Accept": "application/json",
                "User-Agent": "reconagent-razorpay-client",
            },
            follow_redirects=False,
            transport=transport,
        )

    @classmethod
    def from_settings(
        cls,
        settings: Settings,
        **overrides: Any,
    ) -> "RazorpayClient":
        """Build a client from application settings; fail clearly if unset."""
        if not settings.razorpay_configured:
            raise RazorpayError(
                "Razorpay integration is not configured: set RAZORPAY_KEY_ID "
                "and RAZORPAY_KEY_SECRET"
            )
        return cls(
            key_id=settings.razorpay_key_id,
            key_secret=settings.razorpay_key_secret.get_secret_value(),
            base_url=settings.razorpay_base_url,
            timeout_seconds=settings.razorpay_timeout_seconds,
            max_retries=settings.razorpay_max_retries,
            retry_base_delay_seconds=settings.razorpay_retry_base_delay_seconds,
            retry_max_delay_seconds=settings.razorpay_retry_max_delay_seconds,
            jitter=random.uniform if settings.razorpay_retry_jitter else None,
            **overrides,
        )

    @property
    def base_url(self) -> str:
        return self._base_url

    @property
    def key_mode(self) -> str:
        """Credential mode: ``test``, ``live``, or ``unknown`` (never the id)."""
        return self._key_mode

    @property
    def max_retries(self) -> int:
        return self._max_retries

    @property
    def retry_base_delay(self) -> float:
        return self._retry_base_delay

    @property
    def retry_max_delay(self) -> float:
        return self._retry_max_delay

    def close(self) -> None:
        self._client.close()

    @property
    def is_closed(self) -> bool:
        return self._client.is_closed

    def __enter__(self) -> "RazorpayClient":
        return self

    def __exit__(self, *exc_info: object) -> None:
        self.close()

    # --- verb helpers -------------------------------------------------

    def get(self, path: str, *, params: dict[str, Any] | None = None) -> Any:
        """GET a resource; returns parsed JSON (dict/list) or None if empty."""
        return self.request("GET", path, params=params)

    def post(self, path: str, *, json: Any = None) -> Any:
        return self.request("POST", path, json=json)

    def put(self, path: str, *, json: Any = None) -> Any:
        return self.request("PUT", path, json=json)

    def patch(self, path: str, *, json: Any = None) -> Any:
        return self.request("PATCH", path, json=json)

    def delete(self, path: str) -> Any:
        return self.request("DELETE", path)

    def request(
        self,
        method: str,
        path: str,
        *,
        params: dict[str, Any] | None = None,
        json: Any = None,
    ) -> Any:
        """Send one request with bounded retry on transient failures."""
        url_path = path.lstrip("/")
        # Logging target strips any query string: parameters are never
        # written to logs, only the endpoint path.
        log_path = url_path.partition("?")[0]
        correlation_id = uuid4().hex[:12]
        response = self._send_with_retries(
            method, url_path, log_path=log_path,
            correlation_id=correlation_id, params=params, json=json,
        )
        return self._process(response, method, url_path)

    # --- internals ----------------------------------------------------

    def _log(
        self,
        level: int,
        event: str,
        correlation_id: str,
        method: str,
        path: str,
        **fields: Any,
    ) -> None:
        """Emit one structured JSON log line (never credentials/queries)."""
        payload = {
            "event": event,
            "correlation_id": correlation_id,
            "method": method,
            "path": path,
            **fields,
        }
        logger.log(level, json.dumps(payload, sort_keys=True))

    @staticmethod
    def _elapsed_ms(started: float) -> float:
        return round((time.perf_counter() - started) * 1000, 2)

    def _should_retry_read(self, method: str, attempt: int) -> bool:
        return (
            method in ReadMethodsWithRetries and attempt <= self._max_retries
        )

    def _stepped_backoff(self, attempt: int) -> float:
        """Exponential backoff capped at the configured maximum.

        When a jitter function is configured its output is clamped into
        ``[0, max_delay]`` so pathological jitter implementations cannot
        produce negative sleeps or unbounded waits.
        """
        raw = min(
            self._retry_base_delay * (RETRY_BACKOFF_MULTIPLIER ** (attempt - 1)),
            self._retry_max_delay,
        )
        if self._jitter is None:
            return raw
        return min(max(self._jitter(raw), 0.0), self._retry_max_delay)

    def _send_with_retries(
        self,
        method: str,
        url_path: str,
        *,
        log_path: str,
        correlation_id: str,
        params: dict[str, Any] | None,
        json: Any,
    ) -> httpx.Response:
        attempt = 0
        while True:
            attempt += 1
            started = time.perf_counter()
            try:
                response = self._client.request(
                    method, url_path, params=params, json=json
                )
            except httpx.TimeoutException as exc:
                duration_ms = self._elapsed_ms(started)
                if self._should_retry_read(method, attempt):
                    delay = self._stepped_backoff(attempt)
                    self._log(
                        logging.WARNING, "retry_scheduled",
                        correlation_id, method, log_path,
                        error=type(exc).__name__, duration_ms=duration_ms,
                        attempt=attempt, max_retries=self._max_retries,
                        delay_seconds=round(delay, 3),
                    )
                    self._sleep(delay)
                    continue
                raise RazorpayConnectionError(
                    f"Razorpay API request timed out after "
                    f"{self._timeout_seconds}s ({type(exc).__name__})"
                ) from exc
            except httpx.TransportError as exc:
                duration_ms = self._elapsed_ms(started)
                if self._should_retry_read(method, attempt):
                    delay = self._stepped_backoff(attempt)
                    self._log(
                        logging.WARNING, "retry_scheduled",
                        correlation_id, method, log_path,
                        error=type(exc).__name__, duration_ms=duration_ms,
                        attempt=attempt, max_retries=self._max_retries,
                        delay_seconds=round(delay, 3),
                    )
                    self._sleep(delay)
                    continue
                raise RazorpayConnectionError(
                    f"Razorpay API connection failed ({type(exc).__name__})"
                ) from exc

            duration_ms = self._elapsed_ms(started)
            if (
                is_transient_status(response.status_code)
                and method in ReadMethodsWithRetries
                and attempt <= self._max_retries
            ):
                delay = self._retry_delay(response, attempt)
                self._log(
                    logging.WARNING, "retry_scheduled",
                    correlation_id, method, log_path,
                    status=response.status_code, duration_ms=duration_ms,
                    attempt=attempt, max_retries=self._max_retries,
                    delay_seconds=round(delay, 3),
                )
                self._sleep(delay)
                continue

            self._log(
                logging.DEBUG if response.is_success else logging.WARNING,
                "http_response",
                correlation_id, method, log_path,
                status=response.status_code, duration_ms=duration_ms,
                attempt=attempt,
            )
            return response

    def _retry_delay(self, response: httpx.Response, attempt: int) -> float:
        """Honor Retry-After when sane; otherwise stepped backoff.

        A server-provided ``Retry-After`` is honored exactly (capped at the
        configured maximum) and deliberately not jittered — the server told
        us precisely when to come back.
        """
        retry_after = response.headers.get("Retry-After")
        if retry_after is not None:
            try:
                seconds = float(retry_after)
            except ValueError:
                seconds = None
            else:
                seconds = (
                    None
                    if seconds < 0
                    else min(seconds, self._retry_max_delay)
                )
            if seconds is not None:
                return seconds
        return self._stepped_backoff(attempt)

    def _process(
        self, response: httpx.Response, method: str, url_path: str
    ) -> Any:
        if 200 <= response.status_code < 300:
            return self._parse_success_body(response)
        raise self._error_for(response)

    @staticmethod
    def _parse_success_body(response: httpx.Response) -> Any:
        if not response.content:
            return None
        try:
            return response.json()
        except ValueError as exc:
            raise RazorpayInvalidResponseError(
                f"Razorpay returned malformed JSON (HTTP {response.status_code})"
            ) from exc

    @staticmethod
    def _error_for(response: httpx.Response) -> RazorpayError:
        status = response.status_code
        try:
            payload: object = response.json()
        except ValueError:
            payload = None
        detail = RazorpayErrorDetail.from_payload(payload)
        summary = detail.describe() or "no error detail provided"
        message = f"Razorpay API error (HTTP {status}): {summary}"

        exception_class: type[RazorpayError]
        if status in _AUTHENTICATION_STATUSES:
            exception_class = RazorpayAuthenticationError
        elif status in _VALIDATION_STATUSES:
            exception_class = RazorpayValidationError
        elif status == _NOT_FOUND_STATUS:
            exception_class = RazorpayNotFoundError
        elif status == RATE_LIMIT_STATUS:
            exception_class = RazorpayRateLimitError
        elif 500 <= status <= 599:
            exception_class = RazorpayServerError
        else:
            exception_class = RazorpayError

        return exception_class(message, status_code=status, detail=detail)
