"""add payments settlements sync_runs

Revision ID: c61429b4e8f4
Revises: 
Create Date: 2026-08-23 14:56:29.043367

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c61429b4e8f4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('invoice_id', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('captured', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('provider_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_payment_id', name='uq_payments_razorpay_payment_id')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index('ix_payments_provider_created_at', 'payments', ['provider_created_at'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('razorpay_settlement_id', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('fees_minor', sa.BigInteger(), nullable=False),
    sa.Column('tax_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('utr', sa.String(length=64), nullable=True),
    sa.Column('provider_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_settlement_id', name='uq_settlements_razorpay_settlement_id')
    )
    op.create_index('ix_settlements_provider_created_at', 'settlements', ['provider_created_at'], unique=False)
    op.create_index('ix_settlements_utr', 'settlements', ['utr'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payments_fetched', sa.Integer(), nullable=False),
    sa.Column('payments_inserted', sa.Integer(), nullable=False),
    sa.Column('payments_updated', sa.Integer(), nullable=False),
    sa.Column('settlements_fetched', sa.Integer(), nullable=False),
    sa.Column('settlements_inserted', sa.Integer(), nullable=False),
    sa.Column('settlements_updated', sa.Integer(), nullable=False),
    sa.Column('payments_watermark_epoch', sa.BigInteger(), nullable=True),
    sa.Column('settlements_watermark_epoch', sa.BigInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'success', 'partial_failure', 'failed')", name='ck_sync_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_runs_started_at', 'sync_runs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sync_runs_started_at', table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index('ix_settlements_utr', table_name='settlements')
    op.drop_index('ix_settlements_provider_created_at', table_name='settlements')
    op.drop_table('settlements')
    op.drop_index('ix_payments_provider_created_at', table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
